-- EXERCISE 1
CREATE DATABASE HOSPITAL;

CREATE TABLE DOCTOR(
ID INT PRIMARY KEY NOT NULL,
NAME VARCHAR(30) NOT NULL,
SPECIALIZATION VARCHAR(40) NOT NULL,
CONTACT_NUMBER INT NOT NULL);

SELECT * FROM DOCTOR;

CREATE TABLE APPOINTMENTS(
DOCTOR_ID INT NOT NULL,
APPOINTMENT_DATE DATE NOT NULL,
APPOINTMENT_TIME INT NOT NULL,
APPOINTMENT_DURATION INT NULL);

SELECT * FROM APPOINTMENTS;

CREATE TABLE PATIENT(
PATIENT_ID INT PRIMARY KEY NOT NULL,
PATIENT_NAME VARCHAR(36) NOT NULL,
GENDER VARCHAR(10) NOT NULL,
BLOOD_GROUP VARCHAR(20) NOT NULL);

SELECT * FROM PATIENT;

CREATE TABLE REVIEWS(
RATING INT NOT NULL,
FEEDBACK VARCHAR(40) NOT NULL);
SELECT * FROM REVIEWS;

-- EXERCISE 2

CREATE TABLE Contact_table(
id INT PRIMARY KEY NOT NULL,
Email VARCHAR(40) NOT NULL,
fname VARCHAR(30) NOT NULL,
lname VARCHAR(30) NOT NULL,
Company VARCHAR(40) NOT NULL,
Active_flag INT NOT NULL,
opt_out INT NOT NULL);

INSERT INTO Contact_table VALUES(123,'a@a.com','Kian','Seth','ABC',1,1),
(133,'b@a.com','Neha','Seth','ABC',1,0),
(234,'c@c.com','Puru','Malik','CDF',0,0),
(342,'d@d.com','Sid','Maan','TEG',1,0);
 
SELECT * FROM Contact_table;
-- 1
SELECT * FROM Contact_table WHERE Active_flag=1;
SELECT * FROM Contact_table;
-- 2
DELETE FROM Contact_table  WHERE opt_out=1;
SELECT * FROM Contact_table;
-- 3
DELETE FROM Contact_table  WHERE company ='ABC';
SELECT * FROM Contact_table;
-- 4
INSERT INTO Contact_table VALUES(658,'mili@gmail.com','mili','Maan','DGH',1,1);
SELECT * FROM Contact_table;
-- 5
SELECT DISTINCT Company FROM Contact_table ;

-- 6
UPDATE Contact_table SET fname='niti' WHERE fname='mili';
 SELECT * FROM Contact_table;
 
 
 -- EXERCISE 3
 CREATE TABLE CUSTOMERS(
 CUSTOMER_ID INT PRIMARY KEY NOT NULL,
 CUST_NAME VARCHAR(30) NOT NULL,
 CITY VARCHAR(40) NOT NULL,
 GRADE INT NOT NULL,
 SALESMAN_ID INT NOT NULL);
 
 SELECT * FROM CUSTOMERS;
 
 INSERT INTO CUSTOMERS VALUES(3002,'Nick Rimando','New York',100,5001),(3007,'Brad Davis','New York',200,5001),
 (3005,'Graham Zusi','California',200,5002), (3008,'Julian Green','London',200,5002), (3004,'Fabian Johnson','Paris',300,5006),
  (3009,'Geoff Cameron','Berlin',100,5003), (3003,'Jozy Altidor','MoscoW',200,5007), (3001,'Brad Guzan','London',100,5001);
 
 SELECT * FROM CUSTOMERS;
 SELECT CUST_NAME,CITY,GRADE,SALESMAN_ID FROM CUSTOMERS WHERE GRADE <100 ORDER BY CUSTOMER_ID ASC;